### ISSUE TITLE
app_docker and node.docker shouldn't be in the same step (step 4) during the build 

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays_build#15] opened 2017-03-08 11:06 UTC
```root@js8-811:/opt/code/ays_build# ays run
Compute dependency graph...
RUN:213e4de1e08e96d7b5de259be7f219e5
-------
## step:1

step:1 (new)
- packetnet_client          main                      ! install         (new)
- sshkey                    main3                     ! install         (new)

## step:2

step:2 (new)
- node.packet.net           builder                   ! install         (new)

## step:3

step:3 (new)
- os.ssh.ubuntu             builder                   ! install         (new)

## step:4

step:4 (new)
- node.docker               shellinabox               ! install         (new)
- node.docker               caddy                     ! install         (new)
- node.docker               golang                    ! install         (new)
- node.docker               influxdb                  ! install         (new)
- node.docker               nodejs                    ! install         (new)
- node.docker               python                    ! install         (new)
- node.docker               grafana                   ! install         (new)
- node.docker               redis                     ! install         (new)
- node.docker               mongodb                   ! install         (new)
- app_docker                builder                   ! install         (new)
- node.docker               nginx                     ! install         (new)
```

**Comment by xmonader** [comment] 2017-03-15 13:54
Duplicate of #13

**Closed by xmonader** 2017-03-15 13:54 UTC
Labels: type_bug
